using SimulationsProjet


println("================================================")
println("Simulation avec une loi de Poisson")
println("================================================")
SimulationsProjet.classement_stats(SimulationsProjet.simuler_n_fois(10000, SimulationsProjet.ModelePoisson()))
println("")
println("================================================")
println("================================================")
println("Simulation avec une loi de Poisson Bivariee")
println("================================================")
SimulationsProjet.classement_stats(SimulationsProjet.simuler_n_fois(10000, SimulationsProjet.ModelePoissonBivariee()))
println("")
println("================================================")
println("================================================")
println("Simulation avec une loi Binomiale Negative")
println("================================================")
SimulationsProjet.classement_stats(SimulationsProjet.simuler_n_fois(10000, SimulationsProjet.ModeleBinomialeNegative()))
println("")
println("================================================")
println("================================================")
println("Simulation avec le modele de Dixon-Coles")
println("================================================")
SimulationsProjet.classement_stats(SimulationsProjet.simuler_n_fois(10000, SimulationsProjet.ModeleDixonColes()))
println("")
println("================================================")
println("================================================")
println("Simulation avec le modele de Dixon-Coles et les poids Elo")
println("================================================")
SimulationsProjet.classement_stats(SimulationsProjet.simuler_n_fois(10000, SimulationsProjet.ModeleDixonColes(), "Elo"))
